const BLUE_COLOR  = "#01C4D4"
const GREY_COLOR = "#CCCCCC"
const BLACK_COLOR = "#000000"
const WHITE_COLOR = "#FFF"
const PURPLE_COLOR = "#7383C0"
const YELLOW_COLOR = "#F9AE2B"
const GREY_1_COLOR = "#818C9B"
const RED_COLOR = "#e74c3c";

export {
  BLUE_COLOR,
  GREY_COLOR,
  BLACK_COLOR,
  PURPLE_COLOR,
  YELLOW_COLOR,
  WHITE_COLOR,
  GREY_1_COLOR,
  RED_COLOR
}